import SwiftUI

/// Zoom effects inspector panel.
struct ZoomInspector: View {
    @Binding var effects: EffectsConfig

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            // Section: Auto Zoom
            inspectorSection("Auto Zoom") {
                Toggle("Enable auto-zoom on clicks", isOn: $effects.autoZoomEnabled)
                    .font(.system(size: 12))

                Text("Automatically zooms into areas where you click")
                    .font(.caption2)
                    .foregroundStyle(.tertiary)
            }

            if effects.autoZoomEnabled {
                Divider()

                // Section: Scale
                inspectorSection("Scale") {
                    SliderRow(
                        label: "Zoom level",
                        value: $effects.zoomScale,
                        range: 1.2...4.0,
                        defaultValue: EffectsConfig.default.zoomScale,
                        format: "%.1f",
                        unit: "x"
                    )
                }

                Divider()

                // Section: Animation Style
                inspectorSection("Animation") {
                    Picker("Style", selection: $effects.zoomAnimationStyle) {
                        ForEach(ZoomAnimationStyle.allCases, id: \.self) { style in
                            Text(style.displayName).tag(style)
                        }
                    }
                    .pickerStyle(.segmented)
                    .labelsHidden()

                    Text(effects.zoomAnimationStyle.description)
                        .font(.caption2)
                        .foregroundStyle(.tertiary)
                }
            }

            // Section: Zoom Segments
            if !effects.zoomSegments.isEmpty {
                Divider()

                inspectorSection("Zoom Segments") {
                    VStack(spacing: 8) {
                        ForEach($effects.zoomSegments) { $segment in
                            ZoomSegmentRow(segment: $segment, onDelete: {
                                deleteSegment(segment)
                            })
                        }
                    }
                }
            }
        }
    }

    private func deleteSegment(_ segment: ZoomSegment) {
        effects.zoomSegments.removeAll { $0.id == segment.id }
    }
}

// MARK: - Zoom Segment Row

private struct ZoomSegmentRow: View {
    @Binding var segment: ZoomSegment
    let onDelete: () -> Void

    var body: some View {
        HStack(spacing: 8) {
            // Enable/disable toggle
            Toggle("", isOn: $segment.isEnabled)
                .toggleStyle(.checkbox)
                .frame(width: 20)

            // Time range
            VStack(alignment: .leading, spacing: 2) {
                Text("\(formatTime(segment.startTime)) - \(formatTime(segment.endTime))")
                    .font(.system(size: 11, weight: .medium))
                    .foregroundStyle(segment.isEnabled ? .primary : .secondary)

                Text("\(String(format: "%.1f", segment.scale))x • \(segment.isAutoGenerated ? "Auto" : "Manual")")
                    .font(.system(size: 10))
                    .foregroundStyle(.secondary)
            }

            Spacer()

            // Delete button
            Button(action: onDelete) {
                Image(systemName: "xmark.circle.fill")
                    .foregroundStyle(.secondary)
                    .font(.system(size: 14))
            }
            .buttonStyle(.plain)
            .help("Delete zoom segment")
        }
        .padding(.vertical, 4)
        .opacity(segment.isEnabled ? 1.0 : 0.5)
    }

    private func formatTime(_ time: TimeInterval) -> String {
        let minutes = Int(time) / 60
        let seconds = Int(time) % 60
        return String(format: "%d:%02d", minutes, seconds)
    }
}

// MARK: - ZoomAnimationStyle Display

extension ZoomAnimationStyle {
    var displayName: String {
        switch self {
        case .slow: return "Slow"
        case .mellow: return "Mellow"
        case .quick: return "Quick"
        case .rapid: return "Rapid"
        }
    }

    var description: String {
        switch self {
        case .slow: return "Gentle, cinematic zoom transitions"
        case .mellow: return "Smooth, natural-feeling zoom"
        case .quick: return "Snappy, responsive zoom"
        case .rapid: return "Instant, punchy zoom"
        }
    }
}
