name: Frame
options:
  bundleIdPrefix: com.frame
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  minimumXcodeGenVersion: "2.40"
  createIntermediateGroups: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.0"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

targets:
  Frame:
    type: application
    platform: macOS
    sources:
      - path: Frame
        excludes:
          - "**/*.xcassets/*/Contents.json"
          - "**/AGENTS.md"
    resources:
      - path: Frame/Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.frame.app
        PRODUCT_NAME: Frame
        INFOPLIST_FILE: Frame/Info.plist
        CODE_SIGN_ENTITLEMENTS: Frame/Frame.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        ENABLE_HARDENED_RUNTIME: NO
        CODE_SIGN_IDENTITY: "-"
        SWIFT_STRICT_CONCURRENCY: minimal
    info:
      path: Frame/Info.plist
      properties:
        CFBundleName: Frame
        CFBundleShortVersionString: "0.1.0"
        CFBundleVersion: "1"
        LSMinimumSystemVersion: "14.0"
        NSScreenCaptureUsageDescription: "Frame needs screen recording permission to capture your screen."
        NSCameraUsageDescription: "Frame needs camera access to record webcam overlay."
        NSMicrophoneUsageDescription: "Frame needs microphone access to record audio narration."
